/**
 * SST config globals stub.
 * The real types come from .sst/platform/config.d.ts (generated by `sst dev`).
 * This stub exists because .sst is gitignored - it lets the IDE type-check
 * when .sst doesn't exist (e.g. fresh clone, after sst remove).
 */
declare global {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const sst: any;
  const aws: { lambda: { Invocation: new (name: string, args: object) => object } };
  const $dev: boolean;
  const $app: { stage: string; name: string; removal: string };
  const $config: (input: {
    app: (input: { stage?: string }) => object;
    run: () => Promise<object>;
  }) => object;
}

export {};
