/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as DashboardResumeIndexRouteImport } from './routes/dashboard/resume/index'
import { Route as DashboardJobsIndexRouteImport } from './routes/dashboard/jobs/index'
import { Route as DashboardCoverLettersIndexRouteImport } from './routes/dashboard/cover-letters/index'
import { Route as DashboardResumeIdRouteImport } from './routes/dashboard/resume/$id'
import { Route as DashboardJobsIdRouteImport } from './routes/dashboard/jobs/$id'
import { Route as DashboardCoverLettersIdRouteImport } from './routes/dashboard/cover-letters/$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardResumeIndexRoute = DashboardResumeIndexRouteImport.update({
  id: '/dashboard/resume/',
  path: '/dashboard/resume/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardJobsIndexRoute = DashboardJobsIndexRouteImport.update({
  id: '/dashboard/jobs/',
  path: '/dashboard/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCoverLettersIndexRoute =
  DashboardCoverLettersIndexRouteImport.update({
    id: '/dashboard/cover-letters/',
    path: '/dashboard/cover-letters/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardResumeIdRoute = DashboardResumeIdRouteImport.update({
  id: '/dashboard/resume/$id',
  path: '/dashboard/resume/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardJobsIdRoute = DashboardJobsIdRouteImport.update({
  id: '/dashboard/jobs/$id',
  path: '/dashboard/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCoverLettersIdRoute = DashboardCoverLettersIdRouteImport.update({
  id: '/dashboard/cover-letters/$id',
  path: '/dashboard/cover-letters/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/cover-letters/$id': typeof DashboardCoverLettersIdRoute
  '/dashboard/jobs/$id': typeof DashboardJobsIdRoute
  '/dashboard/resume/$id': typeof DashboardResumeIdRoute
  '/dashboard/cover-letters/': typeof DashboardCoverLettersIndexRoute
  '/dashboard/jobs/': typeof DashboardJobsIndexRoute
  '/dashboard/resume/': typeof DashboardResumeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/cover-letters/$id': typeof DashboardCoverLettersIdRoute
  '/dashboard/jobs/$id': typeof DashboardJobsIdRoute
  '/dashboard/resume/$id': typeof DashboardResumeIdRoute
  '/dashboard/cover-letters': typeof DashboardCoverLettersIndexRoute
  '/dashboard/jobs': typeof DashboardJobsIndexRoute
  '/dashboard/resume': typeof DashboardResumeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/cover-letters/$id': typeof DashboardCoverLettersIdRoute
  '/dashboard/jobs/$id': typeof DashboardJobsIdRoute
  '/dashboard/resume/$id': typeof DashboardResumeIdRoute
  '/dashboard/cover-letters/': typeof DashboardCoverLettersIndexRoute
  '/dashboard/jobs/': typeof DashboardJobsIndexRoute
  '/dashboard/resume/': typeof DashboardResumeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/api/$'
    | '/dashboard/'
    | '/dashboard/cover-letters/$id'
    | '/dashboard/jobs/$id'
    | '/dashboard/resume/$id'
    | '/dashboard/cover-letters/'
    | '/dashboard/jobs/'
    | '/dashboard/resume/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/api/$'
    | '/dashboard'
    | '/dashboard/cover-letters/$id'
    | '/dashboard/jobs/$id'
    | '/dashboard/resume/$id'
    | '/dashboard/cover-letters'
    | '/dashboard/jobs'
    | '/dashboard/resume'
  id:
    | '__root__'
    | '/'
    | '/signin'
    | '/signup'
    | '/api/$'
    | '/dashboard/'
    | '/dashboard/cover-letters/$id'
    | '/dashboard/jobs/$id'
    | '/dashboard/resume/$id'
    | '/dashboard/cover-letters/'
    | '/dashboard/jobs/'
    | '/dashboard/resume/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ApiSplatRoute: typeof ApiSplatRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCoverLettersIdRoute: typeof DashboardCoverLettersIdRoute
  DashboardJobsIdRoute: typeof DashboardJobsIdRoute
  DashboardResumeIdRoute: typeof DashboardResumeIdRoute
  DashboardCoverLettersIndexRoute: typeof DashboardCoverLettersIndexRoute
  DashboardJobsIndexRoute: typeof DashboardJobsIndexRoute
  DashboardResumeIndexRoute: typeof DashboardResumeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/resume/': {
      id: '/dashboard/resume/'
      path: '/dashboard/resume'
      fullPath: '/dashboard/resume/'
      preLoaderRoute: typeof DashboardResumeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/jobs/': {
      id: '/dashboard/jobs/'
      path: '/dashboard/jobs'
      fullPath: '/dashboard/jobs/'
      preLoaderRoute: typeof DashboardJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cover-letters/': {
      id: '/dashboard/cover-letters/'
      path: '/dashboard/cover-letters'
      fullPath: '/dashboard/cover-letters/'
      preLoaderRoute: typeof DashboardCoverLettersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/resume/$id': {
      id: '/dashboard/resume/$id'
      path: '/dashboard/resume/$id'
      fullPath: '/dashboard/resume/$id'
      preLoaderRoute: typeof DashboardResumeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/jobs/$id': {
      id: '/dashboard/jobs/$id'
      path: '/dashboard/jobs/$id'
      fullPath: '/dashboard/jobs/$id'
      preLoaderRoute: typeof DashboardJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cover-letters/$id': {
      id: '/dashboard/cover-letters/$id'
      path: '/dashboard/cover-letters/$id'
      fullPath: '/dashboard/cover-letters/$id'
      preLoaderRoute: typeof DashboardCoverLettersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ApiSplatRoute: ApiSplatRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCoverLettersIdRoute: DashboardCoverLettersIdRoute,
  DashboardJobsIdRoute: DashboardJobsIdRoute,
  DashboardResumeIdRoute: DashboardResumeIdRoute,
  DashboardCoverLettersIndexRoute: DashboardCoverLettersIndexRoute,
  DashboardJobsIndexRoute: DashboardJobsIndexRoute,
  DashboardResumeIndexRoute: DashboardResumeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
