/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSuppliersRouteImport } from './routes/admin/suppliers'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSalesOrdersRouteImport } from './routes/admin/sales-orders'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminLocationsRouteImport } from './routes/admin/locations'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminEquipmentRouteImport } from './routes/admin/equipment'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuppliersRoute = AdminSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesOrdersRoute = AdminSalesOrdersRouteImport.update({
  id: '/sales-orders',
  path: '/sales-orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipmentRoute = AdminEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/search': typeof SearchRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/equipment': typeof AdminEquipmentRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales-orders': typeof AdminSalesOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/$': typeof ApiSplatRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/search': typeof SearchRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/equipment': typeof AdminEquipmentRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales-orders': typeof AdminSalesOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/$': typeof ApiSplatRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/search': typeof SearchRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/equipment': typeof AdminEquipmentRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales-orders': typeof AdminSalesOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/$': typeof ApiSplatRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/search'
    | '/admin/categories'
    | '/admin/equipment'
    | '/admin/inventory'
    | '/admin/locations'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/sales-orders'
    | '/admin/settings'
    | '/admin/suppliers'
    | '/admin/users'
    | '/api/$'
    | '/categories/$slug'
    | '/products/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/search'
    | '/admin/categories'
    | '/admin/equipment'
    | '/admin/inventory'
    | '/admin/locations'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/sales-orders'
    | '/admin/settings'
    | '/admin/suppliers'
    | '/admin/users'
    | '/api/$'
    | '/categories/$slug'
    | '/products/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/search'
    | '/admin/categories'
    | '/admin/equipment'
    | '/admin/inventory'
    | '/admin/locations'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/sales-orders'
    | '/admin/settings'
    | '/admin/suppliers'
    | '/admin/users'
    | '/api/$'
    | '/categories/$slug'
    | '/products/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  SearchRoute: typeof SearchRoute
  ApiSplatRoute: typeof ApiSplatRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales-orders': {
      id: '/admin/sales-orders'
      path: '/sales-orders'
      fullPath: '/admin/sales-orders'
      preLoaderRoute: typeof AdminSalesOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipment': {
      id: '/admin/equipment'
      path: '/equipment'
      fullPath: '/admin/equipment'
      preLoaderRoute: typeof AdminEquipmentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminEquipmentRoute: typeof AdminEquipmentRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSalesOrdersRoute: typeof AdminSalesOrdersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSuppliersRoute: typeof AdminSuppliersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminEquipmentRoute: AdminEquipmentRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSalesOrdersRoute: AdminSalesOrdersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSuppliersRoute: AdminSuppliersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  SearchRoute: SearchRoute,
  ApiSplatRoute: ApiSplatRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
