/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ResumePdfIdRouteImport } from './routes/resume-pdf/$id'
import { Route as CoverLetterPdfIdRouteImport } from './routes/cover-letter-pdf/$id'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as DashboardResumesIndexRouteImport } from './routes/dashboard/resumes/index'
import { Route as DashboardJobsIndexRouteImport } from './routes/dashboard/jobs/index'
import { Route as DashboardCoverLettersIndexRouteImport } from './routes/dashboard/cover-letters/index'
import { Route as DashboardResumesIdRouteImport } from './routes/dashboard/resumes/$id'
import { Route as DashboardCoverLettersIdRouteImport } from './routes/dashboard/cover-letters/$id'
import { Route as DashboardResumesIdIndexRouteImport } from './routes/dashboard/resumes/$id/index'
import { Route as DashboardCoverLettersIdIndexRouteImport } from './routes/dashboard/cover-letters/$id/index'
import { Route as DashboardResumesIdStepRouteImport } from './routes/dashboard/resumes/$id/$step'
import { Route as DashboardCoverLettersIdStepRouteImport } from './routes/dashboard/cover-letters/$id/$step'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ResumePdfIdRoute = ResumePdfIdRouteImport.update({
  id: '/resume-pdf/$id',
  path: '/resume-pdf/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverLetterPdfIdRoute = CoverLetterPdfIdRouteImport.update({
  id: '/cover-letter-pdf/$id',
  path: '/cover-letter-pdf/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardResumesIndexRoute = DashboardResumesIndexRouteImport.update({
  id: '/resumes/',
  path: '/resumes/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsIndexRoute = DashboardJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoverLettersIndexRoute =
  DashboardCoverLettersIndexRouteImport.update({
    id: '/cover-letters/',
    path: '/cover-letters/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardResumesIdRoute = DashboardResumesIdRouteImport.update({
  id: '/resumes/$id',
  path: '/resumes/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoverLettersIdRoute = DashboardCoverLettersIdRouteImport.update({
  id: '/cover-letters/$id',
  path: '/cover-letters/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResumesIdIndexRoute = DashboardResumesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardResumesIdRoute,
} as any)
const DashboardCoverLettersIdIndexRoute =
  DashboardCoverLettersIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardCoverLettersIdRoute,
  } as any)
const DashboardResumesIdStepRoute = DashboardResumesIdStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => DashboardResumesIdRoute,
} as any)
const DashboardCoverLettersIdStepRoute =
  DashboardCoverLettersIdStepRouteImport.update({
    id: '/$step',
    path: '/$step',
    getParentRoute: () => DashboardCoverLettersIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/$': typeof ApiSplatRoute
  '/cover-letter-pdf/$id': typeof CoverLetterPdfIdRoute
  '/resume-pdf/$id': typeof ResumePdfIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/cover-letters/$id': typeof DashboardCoverLettersIdRouteWithChildren
  '/dashboard/resumes/$id': typeof DashboardResumesIdRouteWithChildren
  '/dashboard/cover-letters/': typeof DashboardCoverLettersIndexRoute
  '/dashboard/jobs/': typeof DashboardJobsIndexRoute
  '/dashboard/resumes/': typeof DashboardResumesIndexRoute
  '/dashboard/cover-letters/$id/$step': typeof DashboardCoverLettersIdStepRoute
  '/dashboard/resumes/$id/$step': typeof DashboardResumesIdStepRoute
  '/dashboard/cover-letters/$id/': typeof DashboardCoverLettersIdIndexRoute
  '/dashboard/resumes/$id/': typeof DashboardResumesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/$': typeof ApiSplatRoute
  '/cover-letter-pdf/$id': typeof CoverLetterPdfIdRoute
  '/resume-pdf/$id': typeof ResumePdfIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/cover-letters': typeof DashboardCoverLettersIndexRoute
  '/dashboard/jobs': typeof DashboardJobsIndexRoute
  '/dashboard/resumes': typeof DashboardResumesIndexRoute
  '/dashboard/cover-letters/$id/$step': typeof DashboardCoverLettersIdStepRoute
  '/dashboard/resumes/$id/$step': typeof DashboardResumesIdStepRoute
  '/dashboard/cover-letters/$id': typeof DashboardCoverLettersIdIndexRoute
  '/dashboard/resumes/$id': typeof DashboardResumesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/$': typeof ApiSplatRoute
  '/cover-letter-pdf/$id': typeof CoverLetterPdfIdRoute
  '/resume-pdf/$id': typeof ResumePdfIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/cover-letters/$id': typeof DashboardCoverLettersIdRouteWithChildren
  '/dashboard/resumes/$id': typeof DashboardResumesIdRouteWithChildren
  '/dashboard/cover-letters/': typeof DashboardCoverLettersIndexRoute
  '/dashboard/jobs/': typeof DashboardJobsIndexRoute
  '/dashboard/resumes/': typeof DashboardResumesIndexRoute
  '/dashboard/cover-letters/$id/$step': typeof DashboardCoverLettersIdStepRoute
  '/dashboard/resumes/$id/$step': typeof DashboardResumesIdStepRoute
  '/dashboard/cover-letters/$id/': typeof DashboardCoverLettersIdIndexRoute
  '/dashboard/resumes/$id/': typeof DashboardResumesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/api/$'
    | '/cover-letter-pdf/$id'
    | '/resume-pdf/$id'
    | '/dashboard/'
    | '/dashboard/cover-letters/$id'
    | '/dashboard/resumes/$id'
    | '/dashboard/cover-letters/'
    | '/dashboard/jobs/'
    | '/dashboard/resumes/'
    | '/dashboard/cover-letters/$id/$step'
    | '/dashboard/resumes/$id/$step'
    | '/dashboard/cover-letters/$id/'
    | '/dashboard/resumes/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/api/$'
    | '/cover-letter-pdf/$id'
    | '/resume-pdf/$id'
    | '/dashboard'
    | '/dashboard/cover-letters'
    | '/dashboard/jobs'
    | '/dashboard/resumes'
    | '/dashboard/cover-letters/$id/$step'
    | '/dashboard/resumes/$id/$step'
    | '/dashboard/cover-letters/$id'
    | '/dashboard/resumes/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/api/$'
    | '/cover-letter-pdf/$id'
    | '/resume-pdf/$id'
    | '/dashboard/'
    | '/dashboard/cover-letters/$id'
    | '/dashboard/resumes/$id'
    | '/dashboard/cover-letters/'
    | '/dashboard/jobs/'
    | '/dashboard/resumes/'
    | '/dashboard/cover-letters/$id/$step'
    | '/dashboard/resumes/$id/$step'
    | '/dashboard/cover-letters/$id/'
    | '/dashboard/resumes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ApiSplatRoute: typeof ApiSplatRoute
  CoverLetterPdfIdRoute: typeof CoverLetterPdfIdRoute
  ResumePdfIdRoute: typeof ResumePdfIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/resume-pdf/$id': {
      id: '/resume-pdf/$id'
      path: '/resume-pdf/$id'
      fullPath: '/resume-pdf/$id'
      preLoaderRoute: typeof ResumePdfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-letter-pdf/$id': {
      id: '/cover-letter-pdf/$id'
      path: '/cover-letter-pdf/$id'
      fullPath: '/cover-letter-pdf/$id'
      preLoaderRoute: typeof CoverLetterPdfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/resumes/': {
      id: '/dashboard/resumes/'
      path: '/resumes'
      fullPath: '/dashboard/resumes/'
      preLoaderRoute: typeof DashboardResumesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs/': {
      id: '/dashboard/jobs/'
      path: '/jobs'
      fullPath: '/dashboard/jobs/'
      preLoaderRoute: typeof DashboardJobsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cover-letters/': {
      id: '/dashboard/cover-letters/'
      path: '/cover-letters'
      fullPath: '/dashboard/cover-letters/'
      preLoaderRoute: typeof DashboardCoverLettersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resumes/$id': {
      id: '/dashboard/resumes/$id'
      path: '/resumes/$id'
      fullPath: '/dashboard/resumes/$id'
      preLoaderRoute: typeof DashboardResumesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cover-letters/$id': {
      id: '/dashboard/cover-letters/$id'
      path: '/cover-letters/$id'
      fullPath: '/dashboard/cover-letters/$id'
      preLoaderRoute: typeof DashboardCoverLettersIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resumes/$id/': {
      id: '/dashboard/resumes/$id/'
      path: '/'
      fullPath: '/dashboard/resumes/$id/'
      preLoaderRoute: typeof DashboardResumesIdIndexRouteImport
      parentRoute: typeof DashboardResumesIdRoute
    }
    '/dashboard/cover-letters/$id/': {
      id: '/dashboard/cover-letters/$id/'
      path: '/'
      fullPath: '/dashboard/cover-letters/$id/'
      preLoaderRoute: typeof DashboardCoverLettersIdIndexRouteImport
      parentRoute: typeof DashboardCoverLettersIdRoute
    }
    '/dashboard/resumes/$id/$step': {
      id: '/dashboard/resumes/$id/$step'
      path: '/$step'
      fullPath: '/dashboard/resumes/$id/$step'
      preLoaderRoute: typeof DashboardResumesIdStepRouteImport
      parentRoute: typeof DashboardResumesIdRoute
    }
    '/dashboard/cover-letters/$id/$step': {
      id: '/dashboard/cover-letters/$id/$step'
      path: '/$step'
      fullPath: '/dashboard/cover-letters/$id/$step'
      preLoaderRoute: typeof DashboardCoverLettersIdStepRouteImport
      parentRoute: typeof DashboardCoverLettersIdRoute
    }
  }
}

interface DashboardCoverLettersIdRouteChildren {
  DashboardCoverLettersIdStepRoute: typeof DashboardCoverLettersIdStepRoute
  DashboardCoverLettersIdIndexRoute: typeof DashboardCoverLettersIdIndexRoute
}

const DashboardCoverLettersIdRouteChildren: DashboardCoverLettersIdRouteChildren =
  {
    DashboardCoverLettersIdStepRoute: DashboardCoverLettersIdStepRoute,
    DashboardCoverLettersIdIndexRoute: DashboardCoverLettersIdIndexRoute,
  }

const DashboardCoverLettersIdRouteWithChildren =
  DashboardCoverLettersIdRoute._addFileChildren(
    DashboardCoverLettersIdRouteChildren,
  )

interface DashboardResumesIdRouteChildren {
  DashboardResumesIdStepRoute: typeof DashboardResumesIdStepRoute
  DashboardResumesIdIndexRoute: typeof DashboardResumesIdIndexRoute
}

const DashboardResumesIdRouteChildren: DashboardResumesIdRouteChildren = {
  DashboardResumesIdStepRoute: DashboardResumesIdStepRoute,
  DashboardResumesIdIndexRoute: DashboardResumesIdIndexRoute,
}

const DashboardResumesIdRouteWithChildren =
  DashboardResumesIdRoute._addFileChildren(DashboardResumesIdRouteChildren)

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCoverLettersIdRoute: typeof DashboardCoverLettersIdRouteWithChildren
  DashboardResumesIdRoute: typeof DashboardResumesIdRouteWithChildren
  DashboardCoverLettersIndexRoute: typeof DashboardCoverLettersIndexRoute
  DashboardJobsIndexRoute: typeof DashboardJobsIndexRoute
  DashboardResumesIndexRoute: typeof DashboardResumesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCoverLettersIdRoute: DashboardCoverLettersIdRouteWithChildren,
  DashboardResumesIdRoute: DashboardResumesIdRouteWithChildren,
  DashboardCoverLettersIndexRoute: DashboardCoverLettersIndexRoute,
  DashboardJobsIndexRoute: DashboardJobsIndexRoute,
  DashboardResumesIndexRoute: DashboardResumesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ApiSplatRoute: ApiSplatRoute,
  CoverLetterPdfIdRoute: CoverLetterPdfIdRoute,
  ResumePdfIdRoute: ResumePdfIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
